[tool.poetry]
name = "eicu-mortality-prediction"
version = "0.1.0"
description = "Mortality prediction through recurrent neural networks on the eICU dataset"
authors = ["André Ferreira <andrecnf@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^0.25.0"
dask = "^2.2"
torch = "^1.1"
plotly = "tqdm"
tqdm = "^4.32"
scikit-learn = "^0.21.3"
datetime = "^4.3"
shap = {git = "https://github.com/AndreCNF/shap.git"}
# [TODO] Add the model-interpreter package through poetry, when it's public
# model-interpreter = {git = "https://github.com/AndreCNF/model-interpreter.git"}

toolz = "^0.10.0"
fsspec = "^0.4.0"
cloudpickle = "^1.2"
graphviz = "^0.11.1"
distributed = "^2.2"
fastparquet = "^0.3.2"
pyyaml = "^5.1"

[tool.poetry.dev-dependencies]
pylint = "^2.3"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
