[tool.poetry]
name = "eicu-mortality-prediction"
version = "0.1.0"
description = "Mortality prediction through recurrent neural networks on the eICU dataset"
authors = ["André Ferreira <andrecnf@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^0.25.0"
dask = "^2.2"
torch = "^1.1"
plotly = "tqdm"
tqdm = "^4.32"
scikit-learn = "^0.21.3"
datetime = "^4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
